// <auto-generated />
namespace project_framwork.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Qna1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Qna1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110101058236_Qna1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
