// <auto-generated />
namespace project_framwork.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Qn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Qn));
        
        string IMigrationMetadata.Id
        {
            get { return "202110101113438_Qn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
