// <auto-generated />
namespace project_framwork.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Question_Answer1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Question_Answer1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110100955176_Question_Answer1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
