// <auto-generated />
namespace project_framwork.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category));
        
        string IMigrationMetadata.Id
        {
            get { return "202110150641154_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
